# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"ImgSize": "00_core.ipynb",
         "ImgLayout": "00_core.ipynb",
         "ImgType": "00_core.ipynb",
         "ImgColor": "00_core.ipynb",
         "duckduckgo_scrape_urls": "00_core.ipynb",
         "rmtree": "00_core.ipynb",
         "download_urls": "00_core.ipynb",
         "duckduckgo_search": "00_core.ipynb",
         "save_urls_to_csv": "00_core.ipynb",
         "download_images_from_csv": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://joedockrill.github.io/jmd_imagescraper/"

git_url = "https://github.com/joedockrill/jmd_imagescraper/tree/master/"

def custom_doc_links(name): return None
