# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"ImgSize": "00_core.ipynb",
         "ImgLayout": "00_core.ipynb",
         "ImgType": "00_core.ipynb",
         "ImgColor": "00_core.ipynb",
         "duckduckgo_scrape_urls": "00_core.ipynb",
         "rmtree": "00_core.ipynb",
         "download_urls": "00_core.ipynb",
         "duckduckgo_search": "00_core.ipynb",
         "save_urls_to_csv": "00_core.ipynb",
         "download_images_from_csv": "00_core.ipynb",
         "delete_on_click": "01_imagecleaner.ipynb",
         "paging_on_click": "01_imagecleaner.ipynb",
         "reload_on_click": "01_imagecleaner.ipynb",
         "folder_on_change": "01_imagecleaner.ipynb",
         "icln_deleted_img": "01_imagecleaner.ipynb",
         "icln_create_widgets": "01_imagecleaner.ipynb",
         "icln_render_batch": "01_imagecleaner.ipynb",
         "ICLN_BATCH_SZ": "01_imagecleaner.ipynb",
         "icln_base_path": "01_imagecleaner.ipynb",
         "icln_folder": "01_imagecleaner.ipynb",
         "icln_batches": "01_imagecleaner.ipynb",
         "icln_pager": "01_imagecleaner.ipynb",
         "icln_grid": "01_imagecleaner.ipynb",
         "icln_empty_folder": "01_imagecleaner.ipynb",
         "display_image_cleaner": "01_imagecleaner.ipynb"}

modules = ["core.py",
           "imagecleaner.py"]

doc_url = "https://joedockrill.github.io/jmd_imagescraper/"

git_url = "https://github.com/joedockrill/jmd_imagescraper/tree/master/"

def custom_doc_links(name): return None
